### ISSUE TITLE
Please help me fix issue "Get postids failed"!

### ISSUE THREAD

**Issue by nguyenducphu** [pellaeon/fb-post-bulk-privacy-edit#10]
Here is return error when I run process.py on Terminal

###
Starting from time.struct_time(tm_year=2010, tm_mon=4, tm_mday=25, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=6, tm_yday=115, tm_isdst=0)
Starting from time.struct_time(tm_year=2010, tm_mon=4, tm_mday=26, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=0, tm_yday=116, tm_isdst=0)
# Many lines smiliar above #

Get postids failed
{"error":{"message":"(#4) Application request limit reached","type":"OAuthException","is_transient":true,"code":4,"fbtrace_id":"HwRckNpKX9J"}}
Traceback (most recent call last):
  File "process.py", line 27, in <module>
    d = json.load(res)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

###

How to fix @pellaeon ?
Thank so much :)

**Comment by nguyenducphu** [comment]
Python latest version on my Mac is 3.7, but this script alway call to 2.7. Maybe it made error?
