### ISSUE TITLE
Can't make it work...

### ISSUE THREAD

**Issue by Cass87** [pellaeon/fb-post-bulk-privacy-edit#2]
=================Using first method =====================
Starting from 1293840000
Get postids failed
{"error":{"message":"An access token is required to request this resource.","type":"OAuthException","code":104,"fbtrace_id":"BaZ9Mqkvyat"}}
Traceback (most recent call last):
  File "process.py", line 24, in <module>
    d = json.load(res)
  File "/usr/lib/python2.7/json/**init**.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/**init**.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

===============Using second method=============
Dealing with 1#154###8702##7
302
Traceback (most recent call last):
  File "process_from_ids.py", line 31, in <module>
    update_time = m1.group(0)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by pellaeon** [comment]
In `process.py`, you need to fill in the token:
`TOKEN`: a valid Facebook OAuth client token that is authorized to read your own timeline, you can go to [Facebook Graph API Explorer](https://developers.facebook.com/tools/explorer), authorize it, and copy its token here.
